### ISSUE TITLE
Does not work correctly with Google Chrome

### ISSUE THREAD

**Issue by VVKot** [dhruvmanila/telescope-bookmarks.nvim#1]
Getting `[telescope-bookmarks] No Google Chrome bookmarks file found at: [my home path]/Library/Application Support/BraveSoftware/Brave-Browser/Default/Bookmarks` on MacOS + `selected_browser = 'google_chrome'`.

It *seems* (based on my limit knowledge of Lua and reading the source code) that here `state.selected_browser` is correctly set to `google_chrome`:

https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/7afec587d3ee332db2414b286c00cdff7a6e1103/lua/telescope/_extensions/bookmarks.lua#L53-L59

but than here is it reset back to `brave` 🤷 

https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/7afec587d3ee332db2414b286c00cdff7a6e1103/lua/telescope/_extensions/bookmarks/google_chrome.lua#L98-L102

**Comment by dhruvmanila** [comment]
Thanks for reporting. On my local machine, everything works. 

Can you provide me the configuration of telescope from your dotfiles?

**Comment by VVKot** [comment]
Sure, here's the relevant snippet: https://github.com/VVKot/dotfiles/blob/fbfe1b03c13e0bdad4cffa113f0bd28081d81a79/config/nvim/lua/plugin/telescope.lua#L14-L41

**Comment by dhruvmanila** [comment]
Thanks for sharing it. It seems the problem is in your config. `defaults`, `pickers` and `extensions` key are on the same level.
```lua
require("telescope").setup {
  defaults = { ... },
  pickers = { ... },
  extensions = { ... },
}
```

**Comment by VVKot** [comment]
Ah that makes sense. It is working now, thanks!
