### ISSUE TITLE
Support for android

### ISSUE THREAD

**Issue by Iamafnan** [dhruvmanila/telescope-bookmarks.nvim#11]
Hey I just checked out your plugin and it found it very useful but it shows this error in my phone
![IMG_20220217_221641](https://user-images.githubusercontent.com/80388154/154529848-1eb590e7-ab92-4ac8-9fe0-c565e423b2db.jpg)

**Comment by dhruvmanila** [comment]
I'm not familiar with Android, but I would be happy to help you implement it if you want. All of the paths are hardcoded into `lua/telescope/_extensions/bookmarks/chrome.lua` file as there's no way to get it programmatically, as per my knowledge. Also, most browsers have only one path where the bookmarks are stored with an exception of Firefox which uses profiles (addressed with `firefox_profile_name` option). Another thing is that Android uses the linux kernel, so the extension is trying to find the bookmarks where it should be in a linux OS.

**Comment by Iamafnan** [comment]
Hey @dhruvmanila i can't get it working so now I am closing this issue
