### ISSUE TITLE
Add support for `Qutebrowser`

### ISSUE THREAD

**Issue by erayaydin** [dhruvmanila/telescope-bookmarks.nvim#15]
Thanks for the plugin :heart: 

Would be great to have support for [Qutebrowser](https://qutebrowser.org/). It's store bookmarks in the `$XDG_CONFIG_DIR/qutebrowser/bookmarks/urls` file with the structure of:

```
url title
```

I'll try to implement and send PR if its welcome.

**Comment by dhruvmanila** [comment]
> Thanks for the plugin :heart: 

Happy to hear that 😄 


> I'll try to implement and send PR if its welcome.

Yes, please go ahead.

**Comment by dhruvmanila** [comment]
@erayaydin Can you try the `feat/qutebrowser` branch?

**Comment by erayaydin** [comment]
I'm on vacation currently, I can try it in September.
