### ISSUE TITLE
Add support for Waterfox browser

### ISSUE THREAD

**Issue by vsedov** [dhruvmanila/telescope-bookmarks.nvim#17]
https://www.waterfox.net/ < 

Its very similar to firefox, i was wondering if profile support for this could also work ? Similarly to firefox ? 

Il tinker around and see if i can get something working :)

**Comment by dhruvmanila** [comment]
Sure, it should work. Try updating the code similar to how chrome-based browsers are structured.

**Comment by dhruvmanila** [comment]
Hey @vsedov, you can try out the `feat/waterfox` branch

**Comment by vsedov** [comment]
ah appolgies ,yeah il see if it works , been busy with study >.<

**Comment by vsedov** [comment]
Yay it works 
Only change is https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/fad3ff794ac1e7e6d09480847f18f51156098248/lua/telescope/_extensions/bookmarks/firefox.lua#L23 here, should be 
```lua
{".waterfox"}
``` 

But yeah, this works, your a legend :)

**Comment by dhruvmanila** [comment]
closed by: cbc1e5a1cd5cffd06f149a460c2d376cff010b15
