### ISSUE TITLE
[Feature Request] Search for Buku Tags

### ISSUE THREAD

**Issue by traumweh** [dhruvmanila/telescope-bookmarks.nvim#18]
As far as I can tell the search does not include tags one can set while adding a bookmark to buku, which would be pretty nice for larger amounts of bookmarks. Maybe in regards to that a config-key (e.g. `buku_include_tags = true`) would be handy as well.

The tags for each entry seem to be stored in the database column `tags`.

Edit: Created pull-request #19

**Comment by dhruvmanila** [comment]
I'm not really sure about this as it seems to clutter the search entries. Can you tell me what's the use-case for this? Like what do the users of `buku` usually use the tags for? 

> which would be pretty nice for larger amounts of bookmarks

Are you saying this will help in filtering similar to directories on the browser?

**Comment by traumweh** [comment]
I think it depends on how one uses tags. If you have lots of bookmarks associated with the same tag, then yes, it would probably become cluttered very fast. That's why I wouldn't enable this functionality by default but as an opt in for those who use it maybe in a similar way to me.

> Are you saying this will help in filtering similar to directories on the browser?

At least for me that analogy works well. As an example: I have quite a few bookmarks of nvim-plugins that all have some variety of tags, e.g. nvim, docs, keybinds, ui, ...
I don't always remember the names of a plugin but if I'd read the name, I would know which one I'm looking for. So limiting the list of shown entries to ones with e.g. the tag "keybinds" would mean I'd have an easier time finding the bookmark I was looking for.

This is also the equivalent of buku's `s`-Prompt, which takes at least one keyword, which is either the exact name of a bookmark or a tag. So this option would mean that the nvim-interface feels similar-ish to buku itself. Except that buku doesn't match fuzzy but exact (case-insensitive).
