### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by dominikhaid** [dhruvmanila/telescope-bookmarks.nvim#2]
The plugin is not working for me with Firefox. I installed lz4.
But I still get the error "Firefox requires the LZ4 compression library (https://github.com/lz4/lz4)"

I think it's coming from the FFI module ?
Is this working in standard Lua without luajit ?
I'm not familiar with Lua, do I have to install luajit ?

**Comment by dhruvmanila** [comment]
Can you provide me with some contextual information?
- OS
- Where and how did you install Neovim?
- `nvim --version`
- Where and how did you install `lz4`?

If you have `lz4` installed, then this error will only occur if the headers cannot be found on the standard path.

**Comment by dominikhaid** [comment]
Sure 
`OS: Debian GNU/Linux 11 (bullseye) x86_64`
`NVIM:
 NVIM v0.5.0-dev+1470-g2dd782851
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/dominik/neovim/neovim/build/config -I/home/dominik/neovim/neovim/src -I/home/dominik/neovim/neovim/.deps/usr/include -I/usr/include -I/home/dominik/neovim/neovim/build/src/nvim/auto -I/home/dominik/neovim/neovim/build/include
Übersetzt von dominik@debian-tux

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/home/dominik/neovim/share/nvim"`

if i type lz4 in the terminal it says refusing to read from a console
it is installed in lz4: /usr/local/bin/lz4
and i installed it as described here with make && sudo make install
https://github.com/lz4/lz4

**Comment by dhruvmanila** [comment]
That's weird, it's working for me using `make && make install`.

Can you provide the output of `make && make install` or `make && sudo make install`? It will output where the headers and libraries were installed to.

> I think it's coming from the FFI module ?

No, the extension is giving the error [here](https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/main/lua/telescope/_extensions/bookmarks/firefox.lua#L16-L20) because `ffi` cannot load the dynamic library. It must probably be because it cannot find them on the standard C path.

Also, please update the extension as I have pushed an update which will give the reason for the failure as well.

**Comment by dominikhaid** [comment]
The output of make && sudo make install.

```
make[1]: Verzeichnis „/home/dominik/lz4/lib“ wird betreten
make[1]: Verzeichnis „/home/dominik/lz4/lib“ wird verlassen
make[1]: Verzeichnis „/home/dominik/lz4/programs“ wird betreten
make[1]: Verzeichnis „/home/dominik/lz4/programs“ wird verlassen
[sudo] Passwort für dominik: 
make[1]: Verzeichnis „/home/dominik/lz4/lib“ wird betreten
Installing libraries in /usr/local/lib
Installing headers in /usr/local/include
lz4 libraries installed
make[1]: Verzeichnis „/home/dominik/lz4/lib“ wird verlassen
make[1]: Verzeichnis „/home/dominik/lz4/programs“ wird betreten
Installing binaries in /usr/local/bin
Installing man pages in /usr/local/share/man/man1
lz4 installation completed
make[1]: Verzeichnis „/home/dominik/lz4/programs“ wird verlassen
```
Is there a variable I can check that should be exported by the system ?

I also updated your plugin and it out puts as you already sayed that it does not find the lz4 path.

```
E5108: Error executing lua ... rks.nvim / lua / telescope / _extensions / bookmarks / firefox.lua: 19: Failed to load the LZ4 compression library (https://github.com/lz4/lz4) due to:
liblz4.so: Cannot open the shared object file: File or directory not found
Press ENTER or type a command 
```

**Comment by dhruvmanila** [comment]
Can you provide the verbose output of `make`? Use `make VERBOSE=1 install` (`sudo` if required)?

Also, can you try a few commands? After each command try to install `lz4` again and open the extension:
- `ldconfig -v` or `/sbin/ldconfig -v` Here, `v` flag means verbose output
- If the output of `echo $LD_CONFIG_PATH` is empty, try `LD_CONFIG_PATH=/usr/local/lib make VERBOSE=1 install`

_`sudo` if required_

**Comment by dominikhaid** [comment]
Hey man, you can close this, it is working now even with Firefox. Cant tell what it was since I had a complete reinstallation of my system.
So everything is fresh, and it could have been everything broken lz4 install or what ever...still thanks for the support

**Comment by dhruvmanila** [comment]
Good to hear its working :)
