### ISSUE TITLE
Add support for Brave Browser beta

### ISSUE THREAD

**Issue by jmwatte** [dhruvmanila/telescope-bookmarks.nvim#22]
Any chance for getting the brave-browser-beta integrated?
thx

**Comment by dhruvmanila** [comment]
Sure! It shouldn't be too difficult. Just add the bookmarks file path in [this table](https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/main/lua/telescope/_extensions/bookmarks/chrome.lua#L10) similar to `chrome_beta`.
