### ISSUE TITLE
Add support for specifying profile name in possible browsers

### ISSUE THREAD

**Issue by liuyuzhenn** [dhruvmanila/telescope-bookmarks.nvim#23]
The plugin provides options of `firefox_profile_name` and `waterfox_profile_name`, but no options for other browers, e.g. **chrome**/**edge**. I'm wondering is there any reason behind this? It is nice to also have options for other browser profile names.

**Comment by dhruvmanila** [comment]
There's no reason. I was not aware that those browsers allow switching between different profiles. I'll look into it and try to implement it. If you're interested in contributing, I would be happy to help.

**Comment by dhruvmanila** [comment]
Hi @liuyuzhenn, can you try `feat/profiles` branch?

**Comment by liuyuzhenn** [comment]
> Hi @liuyuzhenn, can you try `feat/profiles` branch?

Nice! It works for me both on chrome and edge.

**Comment by dhruvmanila** [comment]
The issue will be closed automatically when the linked PR is merged.
