### ISSUE TITLE
Add support for Chromium browser

### ISSUE THREAD

**Issue by abriz97** [dhruvmanila/telescope-bookmarks.nvim#27]
Hi, 

Thank you very much for the plugin! It looks very cool and I would like to make the best use of it.
However, my standard browser is Chromium, which is not listed in the supported browser, although I see support for Chrome.

I tried playing with some of the configurations settings but wasn't able to load my Chromium bookmarks.
The closest I managed to get was to load my Chrome bookmarks in Chromium.

Is there an easy config fix that can allow me to load my Chromium bookmarks in Chrome?
If it can help, these are stored in ~/snap/chromium/common/chromium/Default/Bookmarks

Thank you so much in advance!

**Comment by dhruvmanila** [comment]
Hi, thanks for the feature request. Currently, I can provide support with only the default config directory which in linux should be `~/.config/chromium` but I'm planning to add support to provide custom config directory.

**Comment by dhruvmanila** [comment]
> add support to provide custom config directory.

tracking this in #29

**Comment by abriz97** [comment]
Thank you very much your work!
Unfortunately I installed chromium through snap, meaning that the config directory is not the same as provided.
Looking forward for resolution of #29!
