### ISSUE TITLE
Error with telescope builtin pickers

### ISSUE THREAD

**Issue by radyz** [dhruvmanila/telescope-bookmarks.nvim#3]
Whenever I try to run

```
lua require('telescope.builtin').builtin({include_extensions = true})
```

this particular extension will raise an error with the following message: 

```
5108: Error executing lua ...lugged/telescope.nvim/lua/telescope/builtin/internal.lua:46: bad argument #1 to 'getinfo' (function or level expected)
```

I've narrowed it down to this line https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/internal.lua#L44, not sure what that fn is expecting to get though

**Comment by dhruvmanila** [comment]
I think this should be opened in the plugin repository: https://github.com/nvim-telescope/telescope.nvim :)
