### ISSUE TITLE
FR: Browser tabs

### ISSUE THREAD

**Issue by loeffel-io** [dhruvmanila/telescope-bookmarks.nvim#40]
Selecting currently open tabs would be so helpful to me

**Comment by dhruvmanila** [comment]
Do you mean to fuzzy search through the currently opened tabs in the selected browser?

**Comment by loeffel-io** [comment]
Yes

**Comment by dhruvmanila** [comment]
I don't think that's in the scope of this plugin. The plugin is only meant to be collecting the existing bookmarks and fuzzy search through them. I think it makes more sense to have it as a separate plugin instead because the logic will also be different. For that reason, I'll close this issue.
